version: "3.9"

services:
  php:
    build:
      context: ./docker/php
    container_name: evisa-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    container_name: evisa-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-evisa}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-evisa_secret}
      POSTGRES_USER: ${POSTGRES_USER:-evisa_user}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-evisa}", "-U", "${POSTGRES_USER:-evisa_user}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
       - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

volumes:
  database_data:
