version: "3.9"

services:
  php:
    build:
      context: ./docker/php
    container_name: evisa-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: evisa-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  db_data:
